/*------------------------------------------------------------------------------
    TABLE CREATION
*/------------------------------------------------------------------------------

/*
    Projects table containing all necessary data regarding a project.
    All time sheet entries will have a project related to it.
*/
CREATE TABLE ts_projects (
    id                  NUMBER(6) GENERATED BY DEFAULT AS IDENTITY,
    code                VARCHAR2(16 CHAR) UNIQUE,
    name                VARCHAR2(64 CHAR) NOT NULL,
    department_id       NUMBER(4) NOT NULL,
    project_manager_id  NUMBER(6) NOT NULL,
    start_date          DATE NOT NULL,
    end_date            DATE DEFAULT NULL,
    status              VARCHAR2(16 CHAR) DEFAULT 'ACTIVE' NOT NULL,
    metadata_json       JSON DEFAULT NULL,
    created_at          DATE DEFAULT SYSDATE NOT NULL,
    
    CONSTRAINT pk_ts_projects_id
        PRIMARY KEY (id),
    
    CONSTRAINT fk_ts_projects_dept
        FOREIGN KEY (department_id)
        REFERENCES departments(department_id)
        ON DELETE CASCADE,
    
    CONSTRAINT fk_ts_project_manager
        FOREIGN KEY (project_manager_id)
        REFERENCES employees(employee_id)
        ON DELETE CASCADE,
        
    CONSTRAINT ck_ts_projects_status
        CHECK (status IN ('PLANNED', 'ACTIVE', 'ON_HOLD', 'CLOSED')),
    
    CONSTRAINT ck_ts_projects_dates
        CHECK (end_date IS NULL OR end_date >= start_date)
);

/*
    Timesheet table for each working week for an employee.
    Each timesheet will have a one-to-many realtionship to timesheet entries.
*/
CREATE TABLE ts_timesheets (
    id                  NUMBER(6) GENERATED BY DEFAULT AS IDENTITY,
    employee_id         NUMBER(6) NOT NULL,
    approver_id         NUMBER(6) NOT NULL,
    week_start_date     DATE NOT NULL,
    week_end_date       DATE NOT NULL,
    status              VARCHAR2(16 CHAR) DEFAULT 'DRAFT' NOT NULL,
    submitted_at        DATE DEFAULT NULL,
    approved_at         DATE DEFAULT NULL,
    rejection_reason    VARCHAR2(255 CHAR) DEFAULT NULL,
    created_at          DATE DEFAULT SYSDATE,
    
    CONSTRAINT pk_ts_timesheets_id
        PRIMARY KEY (id),
    
    CONSTRAINT fk_tsheets_employee
        FOREIGN KEY (employee_id)
        REFERENCES employees (employee_id),

    CONSTRAINT fk_tsheets_approver
        FOREIGN KEY (approver_id)
        REFERENCES employees (employee_id),
        
    CONSTRAINT ck_tsheets_status
        CHECK (status IN ('DRAFT', 'SUBMITTED', 'APPROVED', 'REJECTED')),
        
    CONSTRAINT ck_tsheets_week_range
        CHECK (week_end_date = week_start_date + 6),
        
    CONSTRAINT ck_tsheets_submission_dates
        CHECK (
            (submitted_at IS NULL OR submitted_at >= created_at)
            AND (approved_at IS NULL OR approved_at >= submitted_at)
        )
);

/*
    Entry for timesheets detailing the type of work done by week/hour.
*/
CREATE TABLE ts_timesheet_entries (
    id              NUMBER(6) GENERATED BY DEFAULT AS IDENTITY,
    timesheet_id    NUMBER(6) NOT NULL,
    project_id      NUMBER(6) NOT NULL,
    work_date       DATE,
    hours_worked    NUMBER(2) NOT NULL,
    work_type       VARCHAR2(16 CHAR) DEFAULT 'IN OFFICE',
    entry_note      VARCHAR2(255 CHAR) DEFAULT NULL,
    created_at      DATE DEFAULT SYSDATE,
    
    CONSTRAINT pk_ts_timesheet_entries_id
        PRIMARY KEY (id),
        
    CONSTRAINT fk_tsentry_timesheet
        FOREIGN KEY (timesheet_id)
        REFERENCES ts_timesheets (id),

    CONSTRAINT fk_tsentry_project
        FOREIGN KEY (project_id)
        REFERENCES ts_projects (id),

    CONSTRAINT ck_tsentry_hours
        CHECK (hours_worked > 0 AND hours_worked <= 24),
        
    CONSTRAINT ck_tsentry_work_type
        CHECK (work_type IN ('IN OFFICE', 'REMOTE', 'LEAVE', 'MEDICAL'))
);

/*------------------------------------------------------------------------------
    ADDITIONAL INDEXES
*/------------------------------------------------------------------------------

CREATE INDEX idx_tsheets_status_week
    ON ts_timesheets (status, week_start_date);

CREATE INDEX idx_tsentry_work_date
    ON ts_timesheet_entries (work_date);

CREATE INDEX idx_tsprojects_status
    ON ts_projects (status);



