/*
    DROP and CREATE the debug_log table.
    If an error other than '-942' (Table does not exist) occurs, raise it.
*/

BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE debug_log CASCADE CONSTRAINTS PURGE';
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE != -942 THEN
         RAISE;
      END IF;
END;
/

CREATE TABLE debug_log ( 
    log_id        NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, 
    log_time      TIMESTAMP DEFAULT SYSTIMESTAMP, 
    module_name   VARCHAR2(100), 
    line_no       NUMBER, 
    log_message   VARCHAR2(4000),
    session_id    VARCHAR2(50) DEFAULT SYS_CONTEXT('USERENV', 'SESSIONID') 
);