-- =========================================
-- DIMENSION TABLES
-- =========================================

CREATE TABLE dim_date (
    date_key        NUMBER PRIMARY KEY,
    full_date       DATE NOT NULL,
    day_number      NUMBER NOT NULL,
    day_name        VARCHAR2(20) NOT NULL,
    month_number    NUMBER NOT NULL,
    month_name      VARCHAR2(20) NOT NULL,
    quarter_num     NUMBER NOT NULL,
    year_num        NUMBER NOT NULL,

    CONSTRAINT uq_dim_date_full_date UNIQUE (full_date),
    CONSTRAINT chk_dim_date_day_number CHECK (day_number BETWEEN 1 AND 31),
    CONSTRAINT chk_dim_date_month_number CHECK (month_number BETWEEN 1 AND 12),
    CONSTRAINT chk_dim_date_quarter CHECK (quarter_num BETWEEN 1 AND 4)
);

CREATE TABLE dim_employee (
    employee_key        NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_id         VARCHAR2(200) NOT NULL,
    employee_email      VARCHAR2(100),
    employee_full_name  VARCHAR2(100) NOT NULL,
    job_title           VARCHAR2(100),
    department_name     VARCHAR2(100),
    manager_id          NUMBER,

    CONSTRAINT uq_dim_employee_employee_id UNIQUE (employee_id),
    CONSTRAINT uq_dim_employee_email UNIQUE (employee_email)
);

CREATE TABLE dim_activities (
    activity_key        NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    activity_category   VARCHAR2(30) NOT NULL,
    activity_type       VARCHAR2(100) NOT NULL,
    project_id          NUMBER,
    project_name        VARCHAR2(100),
    title               VARCHAR2(200),

    CONSTRAINT chk_dim_activities_category
        CHECK (activity_category IN ('TIMESHEET', 'ABSENCE', 'CONFLUENCE'))
);

-- =========================================
-- FACT TABLE
-- =========================================

CREATE TABLE fact_employee_day (
    employee_day_key    NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    date_key            NUMBER NOT NULL,
    employee_key        NUMBER NOT NULL,
    activity_key        NUMBER NOT NULL,
    hours               NUMBER(5,2) NOT NULL,

    CONSTRAINT fk_fact_date
        FOREIGN KEY (date_key) REFERENCES dim_date(date_key),

    CONSTRAINT fk_fact_employee
        FOREIGN KEY (employee_key) REFERENCES dim_employee(employee_key),

    CONSTRAINT fk_fact_activity
        FOREIGN KEY (activity_key) REFERENCES dim_activities(activity_key),

    CONSTRAINT chk_fact_hours
        CHECK (hours >= 0 AND hours <= 24)
);